name: Publish Plugin

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Publish plugin
        uses: Kira-NT/mc-publish@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: WyvElY84
          
          files: |
            build/libs/PineLib*.jar
          
          version: ${{ github.event.release.tag_name }}
          version-type: release
          changelog: ${{ github.event.release.body }}
          
          game-versions: |
            >=1.21
            
          loaders: |
            paper
            spigot
            purpur
